//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eliminatoria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class equipo
    {
        public equipo()
        {
            this.fecha = new HashSet<fecha>();
            this.fecha1 = new HashSet<fecha>();
        }
    
        public int id { get; set; }
       // [Required(ErrorMessage = "El equipo es requerido")]
        public string nombre { get; set; }
        public Nullable<int> puntos { get; set; }
    
        public virtual ICollection<fecha> fecha { get; set; }
        public virtual ICollection<fecha> fecha1 { get; set; }
    }
}
