//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eliminatoria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fecha
    {
        public fecha()
        {
            this.detalle = new HashSet<detalle>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fecha1 { get; set; }
        public Nullable<int> fkIdE1 { get; set; }
        public Nullable<int> fkIdE2 { get; set; }
    
        public virtual ICollection<detalle> detalle { get; set; }
        public virtual equipo equipo { get; set; }
        public virtual equipo equipo1 { get; set; }
    }
}
